"""Repository Intelligence (RI): an evidence-backed, provider-neutral model of
what a repository configures (see docs/adr/0001).

Phase 1 is representation only: domain types, deterministic repository-relative
identity, evidence/provenance, redaction and explanation. Nothing here is wired
into the production scanner, and this package never imports the graph, AWS,
discovery, linking or reachability layers.
"""
from __future__ import annotations

from flowlens.repository.enums import (
    ROOT_CAPABLE_ROLES,
    AmbiguityKind,
    AnchorKind,
    ArtifactKind,
    BackendKind,
    CardinalityKind,
    Confidence,
    ConfigurationRole,
    DeclarationMode,
    EvidenceBasis,
    FactKind,
    InstantiationReason,
    InstantiationStatus,
    LifecycleStage,
    ModuleSourceKind,
    ParseStatus,
    Polarity,
    ProvenanceKind,
    ReadStatus,
    RoleStatus,
    Severity,
    StateFormat,
    VarFileKind,
    min_confidence,
)
from flowlens.repository.evidence import (
    Alternative,
    Ambiguity,
    Evidence,
    Inference,
    Locator,
    ObservedFact,
    independent,
)
from flowlens.repository.explain import explain
from flowlens.repository.model import (
    CURRENT_REPOSITORY_MODEL_VERSION,
    BackendEvidence,
    BlockSummary,
    Cardinality,
    Classification,
    ConfigurationLifecycle,
    DeclarationInventory,
    DeploymentContext,
    DesiredResourceInstance,
    Diagnostic,
    InstantiationRecord,
    MetaArguments,
    ModuleCall,
    ModuleInstance,
    ModuleSource,
    RawArtifact,
    RepositoryAnchor,
    RepositoryModel,
    ResourceDeclaration,
    RoleAssessment,
    SourceFileRef,
    StateArtifact,
    TerraformConfiguration,
    VarFileArtifact,
)

schema_version = CURRENT_REPOSITORY_MODEL_VERSION

__all__ = [
    "CURRENT_REPOSITORY_MODEL_VERSION",
    "ROOT_CAPABLE_ROLES",
    "Alternative",
    "Ambiguity",
    "AmbiguityKind",
    "AnchorKind",
    "ArtifactKind",
    "BackendEvidence",
    "BackendKind",
    "BlockSummary",
    "Cardinality",
    "CardinalityKind",
    "Classification",
    "Confidence",
    "ConfigurationLifecycle",
    "ConfigurationRole",
    "DeclarationInventory",
    "DeclarationMode",
    "DeploymentContext",
    "DesiredResourceInstance",
    "Diagnostic",
    "Evidence",
    "EvidenceBasis",
    "FactKind",
    "Inference",
    "InstantiationReason",
    "InstantiationRecord",
    "InstantiationStatus",
    "LifecycleStage",
    "Locator",
    "MetaArguments",
    "ModuleCall",
    "ModuleInstance",
    "ModuleSource",
    "ModuleSourceKind",
    "ObservedFact",
    "ParseStatus",
    "Polarity",
    "ProvenanceKind",
    "RawArtifact",
    "ReadStatus",
    "RepositoryAnchor",
    "RepositoryModel",
    "ResourceDeclaration",
    "RoleAssessment",
    "RoleStatus",
    "Severity",
    "SourceFileRef",
    "StateArtifact",
    "StateFormat",
    "TerraformConfiguration",
    "VarFileArtifact",
    "VarFileKind",
    "explain",
    "independent",
    "min_confidence",
    "schema_version",
]
